### ISSUE TITLE
nexus Mod Manager Object Reference 

### ISSUE THREAD

**Issue by AdityaHardikar1996** [Nexus-Mods/web-issues#1153]
[TraceLog20200609105942.txt](https://github.com/Nexus-Mods/web-issues/files/4750160/TraceLog20200609105942.txt)

            
            Tracing an Unhandled Exception:
            Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.Games.Witcher3.Witcher3GameModeDescriptor.get_InstallationPath()
   at Nexus.Client.Games.GameDiscoverer.Find(IEnumerable`1 gameModesToFind)
   at Nexus.Client.Bootstrapper.GetInstalledGameModes(GameModeRegistry supportedGameModes)
   at Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   at Nexus.Client.Program.Main(String[] p_strArgs)

            Running Threads (0)

**Comment by Pickysaurus** [comment]
Nexus Mod Manager is unsupported (and has been since December 2016) for support with NMM you can post here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues

We strongly suggest you switch to a modern mod manager (such as Vortex).

https://www.nexusmods.com/about/vortex/?
